# Generated by Django 2.1.12 on 2020-01-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'db_persona',
            },
        ),
    ]
